server {
    listen       8080;
    server_name  _;

    # SPA entrypoint
    root   /usr/share/nginx/html;
    index  index.html;

    # Cluster DNS resolver — required for nginx to re-resolve Service names
    resolver kube-dns.kube-system.svc.cluster.local valid=30s ipv6=off;

    # Static assets (hashed filenames — long cache)
    location ~* \.(?:js|css|woff2?|eot|ttf|svg|png|jpg|jpeg|gif|ico|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Backend API reverse proxies (Kubernetes in-cluster DNS)
    location /api/geoint/ {
        proxy_pass http://geoint.sovdefence.svc.cluster.local:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
    location /api/documents/ {
        proxy_pass http://doc-intel.sovdefence.svc.cluster.local:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
    location /api/osint/ {
        proxy_pass http://osint.sovdefence.svc.cluster.local:8003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
    location /api/sc/ {
        proxy_pass http://supply-chain.sovdefence.svc.cluster.local:8004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
    location /api/compliance/ {
        proxy_pass http://compliance.sovdefence.svc.cluster.local:8005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }

    # SPA fallback — React Router client-side paths
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Health for k8s probes
    location = /healthz {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
