#!/usr/bin/env python3
"""
Read synthetic.json and emit a SQL file with literal INSERTs ready for
SQLcl to slurp. Bypasses python-oracledb wallet setup entirely.

Usage:
  python3 build_inline_load.py            # writes to sibling sql file
"""
from __future__ import annotations

import json
from pathlib import Path


def quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def main() -> int:
    here = Path(__file__).parent
    payload = json.loads((here / "synthetic.json").read_text())
    if not payload.get("header", {}).get("synthetic"):
        raise SystemExit("Refusing: header.synthetic must be true")

    out = here / "load_sample_data_inline.sql"
    with out.open("w") as fh:
        fh.write("-- Auto-generated by build_inline_load.py — do not edit\n")
        fh.write("-- Synthetic UC10 corpus loader. Idempotent via MERGE.\n")
        fh.write("SET DEFINE OFF\nSET FEEDBACK OFF\nSET ECHO OFF\n\n")

        for p in payload.get("programs", []):
            fh.write(
                "MERGE INTO programs p USING (SELECT "
                f"{quote(p['program_id'])} AS program_id FROM dual) s "
                "ON (p.program_id = s.program_id) "
                "WHEN NOT MATCHED THEN INSERT "
                "(program_id, name, domain, security_class, customer_country, "
                "start_year, status, clearance_required, releasable_to) "
                f"VALUES ({quote(p['program_id'])}, {quote(p['name'])}, "
                f"{quote(p.get('domain'))}, {quote(p['security_class'])}, "
                f"{quote(p.get('customer_country'))}, {quote(p.get('start_year'))}, "
                f"{quote(p.get('status'))}, 'RESTRICTED', 'NATO');\n"
            )
        fh.write("\n")
        for r in payload.get("requirements", []):
            fh.write(
                "MERGE INTO requirements r USING (SELECT "
                f"{quote(r['req_id'])} AS req_id FROM dual) s "
                "ON (r.req_id = s.req_id) "
                "WHEN NOT MATCHED THEN INSERT "
                "(req_id, program_id, req_text, req_type, category, status, "
                "clearance_required, releasable_to) "
                f"VALUES ({quote(r['req_id'])}, {quote(r['program_id'])}, "
                f"{quote(r['req_text'])}, {quote(r.get('req_type'))}, "
                f"{quote(r.get('category'))}, {quote(r.get('status'))}, "
                f"{quote(r.get('clearance_required', 'RESTRICTED'))}, "
                f"{quote(r.get('releasable_to', 'NATO'))});\n"
            )
        fh.write("\nCOMMIT;\nEXIT;\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
